---
- name: Ansible REST and tags
  hosts: localhost
  gather_facts: false

  vars:
    myrsakey: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Kep prep
      debug:
        msg: "Your RSA key is {{ myrsakey }}"
      tags:
        - keytime
        - vmprep
