---
- name: A play to play with python
  hosts: localhost

  vars:
    test_list:
      - '192.168.2.1'
      - '10.10.10.2'
      - 'host.example.org'
      - '192.168.70.0/24'
      - 'fe80::100/10'
      - True
      - 'Witcher3 The Wild Hunt'
      - 'Earl Grey Tea, hot'
    mytest_string: "ncc1701 uss enterprise"
    myaddresses: ['192.168.2.101', '10.10.3.50', '171.172.32.1']

  tasks:
    - name: Just want the IPs
      debug:
        msg: "{{ test_list | ipaddr }}"

    - name: Spawn random mac
      debug:
        msg: "{{'52:54:00' | random_mac }}"

    - name: Some do not require mustache brackets
      debug:
        var: "'52:54:11'|random_mac"

    - name: Test if our string ends in prise
      debug:
        msg: "{{ mytest_string.endswith('prise') }}"

    - name: This only prints when this tests true using python
      debug:
        msg: "Ahh but is the enterprise subclass A, B, C, or D?"
      when: mytest_string.endswith('prise')

    - name: Jinja2 way of capitaliziing a string
      debug:
        msg: "{{ mytest_string | capitalize }}"

    - name: Python way of capitalizing a string
      debug:
        msg: "{{ mytest_string.capitalize() }}"

    - name: pop the number 50 on the screem
      debug:
        msg: "{{ (myaddresses|ipaddr('10.0.0.0/8'))[0].split('.')[3] }}"
     
    - name: Reverse order!
      debug:
        msg: "{{ (test_list|replace('True','False')) }}"













